### ISSUE TITLE
Recommended way to update an index?

### ISSUE THREAD

**Issue by curlycabbage** [ndx-search/ndx#11]
Hello, is there a recommended way to update an index in place? 

Building on examples in the [docs](https://github.com/ndx-search/docs#removing-documents-from-the-index), I am using this right now:

```ts
    update: (id, doc) => {
      this.remove(id);
      if (removed.size) vacuumIndex(index, removed);
      this.add(doc);
    },
```

I am worried that vacuumIndex has to recurse the entire tree, and therefore it won't scale as well as add and remove. Is this a valid concern?

**Comment by localvoid** [comment]
> I am worried that vacuumIndex has to recurse the entire tree, and therefore it won't scale as well as add and remove. Is this a valid concern?

Yes, it can be a problem. I don't think that there is a good solution to this problem right now. Here are possible solutions:

1. Generate a new document id each time document is updated and add old document id to `removed` set.
2. Modify `ndx` internals and add `removed` flag to `DocumentDetails`. Mark previous `DocumentDetails` as removed when document is updated/removed instead of using `removed` set.

Second solution is way much better, but it would require changing all APIs and data structures.

**Comment by localvoid** [comment]
Here is a second solution (`ndx` and `ndx-query`): https://gist.github.com/localvoid/29dc5139fc8dcb2ca0de5ffff01e18a6 .

**Comment by curlycabbage** [comment]
Thank you!
