### ISSUE TITLE
v1 release planning suggestion

### ISSUE THREAD

**Issue by vladimiry** [ndx-search/ndx#9]
I think it would make sense to pre-release `v1.0.0-beta1` first in `beta` npm channel. I'm going to try using it then for a while in this project https://github.com/vladimiry/email-securely-app, so that would be an addition beta testing before final release.

**Comment by localvoid** [comment]
Published: [ndx](https://github.com/ndx-search/ndx), [ndx-index](https://github.com/ndx-search/ndx-index), [ndx-query](https://github.com/ndx-search/ndx-query), [ndx-compat](https://github.com/ndx-search/ndx-compat) and [ndx-serializable](https://github.com/ndx-search/ndx-serializable).

**Comment by localvoid** [comment]
Tomorrow I'll try to optimize [ndx-serializable](https://github.com/ndx-search/ndx-serializable) data structures. I'll replace trie data structure for inverted index with two arrays: keys and values. gzip should be able to compress common prefixes for keys.

**Comment by vladimiry** [comment]
I will not be able to try ndx with email-securely-app earlier than in a week or few, doing some refactoring and preparations for full-text feature enabling. Besides the initial implementation is not going to use serialization, but there is going to be such need.

**Comment by vladimiry** [comment]
This release https://github.com/vladimiry/email-securely-app/releases/tag/v2.2.0 uses recently published `ndx` beta version for search. The app doesn't use the serialization yet though. Search has been working great so far. Will provide feedback in a few weeks and then close this issue.

**Comment by localvoid** [comment]
Do you think it would be better if I move all code from `ndx-index` into `ndx`, since it is highly unlikely that there will be an alternative document indexing implementation and it is tightly coupled with the data structure that is used in `ndx`?

Also, as you've noticed `ndx-utils` is quite bad, so I want to move this functions to `ndx-compat` and remove this package. In the documentation I'll just use lodash [`words()`](https://lodash.com/docs/#words) function as a tokenizer.

**Comment by localvoid** [comment]
Also, I want to change [`id`](https://github.com/ndx-search/ndx/blob/c1cdfbe23a133ff49598f0731bd815eb36675956/src/index.ts#L49-L52) property in `DocumentDetails` to `doc` because in some use cases this indirection is useless and we can just store direct refs to document objects. It would also require small change in the `addDocumentIndex()` function, `id` argument will be replaced with an optional argument to specify custom `key` for use cases that want to store some unique keys instead of direct refs.

**Comment by localvoid** [comment]
> Does it mean index will keep a reference to the original/full document argument passed to `addDocumentToIndex`?

Only when `id` isn't specified, I want to make it as a last optional argument in this function. 

> I'd like there will still be an option not storing a reference to a full document, as I don't want full documents to be kept in memory after they got indexed. 

Yes, I understand that such use case is extremely important, I also using it in exactly the same way.

**Comment by vladimiry** [comment]
> I want to make it as a last optional argument in this function

Just a note. If a function gets a lot of arguments, especially if some of them are optional, it might wort considering turning arguments to a single object argument as generally going with an object as an argument is a more flexible option and more self-documented.

**Comment by localvoid** [comment]
I don't think that JIT in v8/others will inline this function and because of it escape analysis won't be able to figure out that it can remove this temporary allocation. Don't want additional memory allocation per each invocation since it is a low-level API.

**Comment by vladimiry** [comment]
Sure. Thanks for thorough analyzing and approach of building this library. One of the reasons I didn't enable serialization with initial search feature release is that indexing and search work quite fast.

**Comment by localvoid** [comment]
Published in the `beta` channel: `ndx`, `ndx-query`, `ndx-compat` and `ndx-serializable`.

Decided to keep it simple without any optional arguments, `addDocumentToIndex()` API hasn't changed. 

- Functions from `ndx-index` moved to `ndx`
- `QueryResult` property name `docId` renamed to `key`. `docId` implied that it should be some kind of an ID.

**Comment by vladimiry** [comment]
The desktop app mentioned above is working well with the following versions:
```
  "ndx": "1.0.0-beta.2",
  "ndx-query": "1.0.0-beta.2",
  "ndx-utils": "1.0.0-beta.0",
```
I didn't notice a memory leaks. Closing the issue as resolved.
